# Generated by Django 4.2.3 on 2023-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='counter',
            field=models.IntegerField(default=4),
        ),
    ]
